name: tlt_manager
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  intl: ^0.17.0
  firebase_messaging: ^9.1.3
  flutter_local_notifications: ^5.0.0+1
  shared_preferences: ^2.0.5
  lottie: ^0.7.0
  flutter_svg: ^0.19.3
  flutter_animator: ^3.1.1
  cached_network_image: ^2.5.1
  connectivity: ^3.0.3
  url_launcher: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/animations/gifs/
    - assets/animations/lottiefiles/
    - assets/icons/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf